name: getx_nested_navigation_example
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 
    git: https://github.com/kumsumit/get.git
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

